# Generated by Django 3.0.7 on 2020-09-01 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='macadress',
        ),
    ]
