# Generated by Django 3.0.7 on 2020-08-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0002_laptop_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
