# Generated by Django 3.0.7 on 2020-09-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0002_remove_laptop_macadress'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='macadress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
